# Generated by Django 4.2.5 on 2024-09-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_record_unique_together_record_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='owner',
            new_name='psm_owner',
        ),
        migrations.AddField(
            model_name='record',
            name='alarm_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='coverage_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='coverage_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='is_skip',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='protection_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tldr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
