# Generated by Django 4.2.5 on 2024-09-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_owner_record_psm_owner_record_alarm_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='last_update_datetime_for_record_4_unique_records',
            new_name='last_updated_datetime',
        ),
    ]
