# Generated by Django 5.0.6 on 2024-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psm', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('domain', models.URLField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('console', models.CharField(max_length=50, null=True)),
                ('operator', models.CharField(max_length=70, null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('last_update_datetime_for_record_4_unique_records', models.CharField(max_length=200, null=True)),
            ],
            options={
                'unique_together': {('psm', 'region', 'domain', 'location', 'category', 'priority', 'console', 'operator', 'owner', 'comments', 'last_update_datetime_for_record_4_unique_records')},
            },
        ),
    ]
